### ISSUE TITLE
Multiple RFID reader

### ISSUE THREAD

**Issue by falhar** [node-hid/node-hid#476]
Hi I'm using node-hid to access two devices RFID reader but when I print HID.devices() it shows both devices have the same vendorId and productId
currently I'm access using path but if reboot server it will randomly read path of the devices, I mean say device 1 with path /hidraw0, device 2 in /hidraw1 then when restart device 1 can be /hidraw1 and device 2 in /hidraw0, how can I access them with vid and pid if they read 2 devices as same vid and pid?

**Comment by Julusian** [comment]
Do they report serial numbers? You can provide the serialnumber as a third parameter when opening the device by vid and pid

**Comment by falhar** [comment]
both the device information are same and only the path is different

**Comment by Julusian** [comment]
I dont know then.

Internally the open by vid&pid is listing all the connected devices and picking the first, then opening that by path. It isnt doing anything that couldnt be done in your own code. I think I have seen that using this method isnt recommended because it is not very efficient.

All I can suggest is to look into why the paths arent stable.
Perhaps if you connect them via a usb hub or directly to the computer the order will become stable?
Or if not, maybe you can look at sysfs to get an identifier that includes the usb port they are connected to? 
Perhaps if you use the libusb backend the ids might be more stable?
